import type { Metadata } from "next";
import { Header } from "@/widgets/layout/Header/Header";
import { Footer } from "@/widgets/layout/Footer/Footer";
import "@/shared/styles/globals.css";
import { Cta } from "@/widgets/layout/Cta/Cta";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Cta />
        <Footer />
      </body>
    </html>
  );
}
